name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-test:
    name: build-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (1.79.0)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: rustfmt, clippy

      - name: Format check
        working-directory: daemon
        run: cargo fmt -- --check

      - name: Clippy
        working-directory: daemon
        run: cargo clippy -q -- -D warnings

      - name: Tests
        working-directory: daemon
        run: cargo test --all --quiet

  windows-release:
    name: windows-release (toolchain 1.79.0)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (1.79.0)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0

      - name: Build release binaries
        working-directory: daemon
        run: |
          cargo build --release --bin colinux-daemon
          cargo build --release --bin smoke

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: colinux-daemon-windows-x64-${{ github.ref_name }}
          path: |
            daemon/target/release/colinux-daemon.exe
            daemon/target/release/smoke.exe

      - name: Enforce no warnings in release
        working-directory: daemon
        env:
          RUSTFLAGS: -D warnings
        run: cargo build --release --bin colinux-daemon --bin smoke

  tagged-release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: draft-release (Windows assets)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (1.79.0)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0

      - name: Build release binaries
        working-directory: daemon
        env:
          RUSTFLAGS: -D warnings
        run: |
          cargo build --release --bin colinux-daemon
          cargo build --release --bin smoke

      - name: Create draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            daemon/target/release/colinux-daemon.exe
            daemon/target/release/smoke.exe
